package org.apache.hadoop.hive.cli;

import junit.framework.Test;
import junit.framework.TestCase;
import junit.framework.TestSuite;

import java.io.*;
import java.util.*;

import org.apache.hadoop.hive.ql.QTestUtil;
import org.apache.hadoop.hive.ql.exec.Task;

import org.antlr.runtime.*;
import org.antlr.runtime.tree.*;

public class $className extends TestCase {

  private QTestUtil qt;

  public $className(String name) {
    super(name);
    qt = null;
  }

  @Override
  protected void setUp() {
    try {
      qt = new QTestUtil("$resultsDir.getCanonicalPath()", "$logDir.getCanonicalPath()");

    }
    catch (Throwable e) {
      e.printStackTrace();
      System.out.flush();
      fail("Unexpected exception in setup");
    }
  }

  public static Test suite() {
    TestSuite suite = new TestSuite();
#foreach ($qf in $qfiles)
  #set ($fname = $qf.getName())
  #set ($eidx = $fname.length() - 2)
  #set ($tname = $fname.substring(0, $eidx))
    suite.addTest(new $className("testNegativeCliDriver_$tname"));
#end
    return suite;
  }

  static String debugHint = "\nSee build/ql/tmp/hive.log, "
     + "or try \"ant test ... -Dtest.silent=false\" to get more logs.";

#foreach ($qf in $qfiles)
  #set ($fname = $qf.getName())
  #set ($eidx = $fname.length() - 2)
  #set ($tname = $fname.substring(0, $eidx))
  public void testNegativeCliDriver_$tname() throws Exception {
    try {
      System.out.println("Begin query: " + "$fname");

      qt.addFile("$qf.getCanonicalPath()");

      if (qt.shouldBeSkipped("$fname")) {
        System.out.println("Test $fname skipped");
        return;
      }
      
      qt.cliInit("$fname");
      int ecode = qt.executeClient("$fname");
      if (ecode == 0) {
        fail("Client Execution failed with error code = " + ecode
            + debugHint);
      }

      ecode = qt.checkCliDriverResults("$fname");
      if (ecode != 0) {
        fail("Client execution results failed with error code = " + ecode
            + debugHint);
      }
    }
    catch (Throwable e) {
      System.out.println("Exception: " + e.getMessage());
      e.printStackTrace();
      System.out.flush();
      fail("Unexpected exception" + debugHint);
    }

    System.out.println("Done query: " + "$fname");
    assertTrue("Test passed", true);
  }

#end
}

